#!/usr/bin/python
import urllib2
import sys
import argparse
import json

DEST_LANG="fr"
SOURCE_LANG="en"

def pull(phrase, source, dest):
	phrase = urllib2.quote(phrase)
	try:
		opener = urllib2.build_opener()
		opener.addheaders = [('User-agent', 'Mozilla/5.0')]
		response = opener.open("http://translate.google.co.uk" + "/translate_a/t?client=webapp&sl=" + source + "&tl=" + dest + "&hl=en&sc=1&q=" + phrase)
	except urllib2.HTTPError, err:
		print "ERROR [" + err + "] Google says no"
		sys.exit(0)
	except:
		print "ERROR [UNKNOWN] Google really says no"
		sys.exit(0)
		
	return json.loads(response.read())
	
	
def parse(reply):
	tran = ""
	for s in reply['sentences']:
		tran+=s['trans']
	return tran

def main():
        parser = argparse.ArgumentParser(description='A command line wrapper for Google Translate')
        parser.add_argument('text', nargs='+', help='Profanities you would like to translate')
        parser.add_argument('-s', default=SOURCE_LANG, metavar="source_lang", help="Language you know")
        parser.add_argument('-d', default=DEST_LANG, metavar="dest_lang", help="Language you wish you knew")
        parser.add_argument('--switch', '-w', action='store_true', help="Switch the default languages")
        args = parser.parse_args()
      	
	if (args.switch is False):  
		print "\033[1;91m" + parse(pull(' '.join(args.text), args.s, args.d))+ "\033[0;39m"
	else: 	
		print "\033[1;91m" + parse(pull(' '.join(args.text), args.d, args.s))+ "\033[0;39m"

if __name__ == '__main__':
	main()
