#!/usr/bin/python
import socket
import urllib
import re
import sys
import argparse

DEST_LANG="fr"
SOURCE_LANG="en"

def pull(phrase, source, dest):
	phrase = urllib.quote(phrase)
	try:
		s=socket.socket()
		s.connect(("translate.google.co.uk",80))
		s.send("GET /translate_a/t?client=webapp&sl=" + source + "&tl=" + dest + "&hl=en&sc=1&q=" + phrase + " HTTP/1.1")
		s.send("\n\n")
		reply = s.recv(1024)
	except:
		print "Google says no"
	
	return reply
	
def parse(reply):
	reply = reply.split('\n')
	
	for line in reply:
		if re.search('"trans"', line):
			chunks = line.split('"')
			return chunks[5]

def main():
        parser = argparse.ArgumentParser(description='A command line wrapper for Google Translate')
        parser.add_argument('text', nargs='+', help='Profanities you would like to translate')
        parser.add_argument('-s', default=SOURCE_LANG, metavar="source_lang", help="Language you know")
        parser.add_argument('-d', default=DEST_LANG, metavar="dest_lang", help="Language you wish you knew")
        parser.add_argument('--switch', '-w', action='store_true', help="Switch the default languages")
        args = parser.parse_args()
      	
	if (args.switch is False):  
		print "\033[1;91m" + parse(pull(' '.join(args.text), args.s, args.d))+ "\033[0;39m"
	else: 	
		print "\033[1;91m" + parse(pull(' '.join(args.text), args.d, args.s))+ "\033[0;39m"

if __name__ == '__main__':
	main()
